// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.DataContext;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(EFDataContext))]
    [Migration("20220516065919_tche")]
    partial class tche
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Models.Consulta", b =>
                {
                    b.Property<Guid?>("ConsultaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Especialidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PacienteModelID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConsultaID");

                    b.HasIndex("PacienteModelID");

                    b.ToTable("TB_Consultas");
                });

            modelBuilder.Entity("Domain.Models.Endereco", b =>
                {
                    b.Property<Guid?>("EnderecoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rua")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnderecoID");

                    b.ToTable("TB_Enderecos", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PacienteModel", b =>
                {
                    b.Property<Guid?>("PacienteModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EnderecoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PacienteModelID");

                    b.HasIndex("EnderecoID");

                    b.ToTable("TB_Pacientes", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Consulta", b =>
                {
                    b.HasOne("Domain.Models.PacienteModel", null)
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteModelID");
                });

            modelBuilder.Entity("Domain.Models.PacienteModel", b =>
                {
                    b.HasOne("Domain.Models.Endereco", "Endereco")
                        .WithMany("Pacientes")
                        .HasForeignKey("EnderecoID");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Domain.Models.Endereco", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("Domain.Models.PacienteModel", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
